language: ruby

branches:
  only:
    - master

rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2

jdk:
  - openjdk7

script: "TEST_CLUSTER_COMMAND=/usr/share/elasticsearch/bin/elasticsearch bundle exec rake test:coverage"
